### PR TITLE
Resolving Running Vercel Build Deployments

### PR DESCRIPTION
**Pull request by IslamiTP**
## Summary of Changes
Removed some lines of code. I removed them because I was trying to fix the bugs when running the `npm run build`.

## Context
I was encountering multiple errors on the **Get Started** page during the build process.

## Request for Review
Let me know if these changes are okay.

### CODE REVIEW

**Comment by ragadalh** [comment]
The changes look good.

**Comment by nawalragih** [comment]
looks good

**Review by ragadalh — APPROVED** [review]
all changes look good

**Review by nawalragih — APPROVED** [review]

**Comment by IslamiTP** [comment]
## Summary of Changes
Removed some lines of code. I removed them because I was trying to fix the bugs when running the `npm run build`.

## Context
I was encountering multiple errors on the **Get Started** page during the build process.

## Files Changed
- `firebase.ts`
- `src/app/login/page.tsx`
- `src/app/schedule/page.tsx`

## Request for Review
Let me know if these changes are okay.

**Pull request merged**
